
version: '3.9'
services:
  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3500 -w db.json
    ports:
      - "3500:3500"
    volumes:
      - ./TradeNationData:/data
    restart: always

  reactapp:
    build: ./TradeNation
    ports:
      - "3000:3000"
    depends_on:
      - json-server
      