#### ------------- Docker Compose ------------- ####
version: "2.9"
services:
  json-server:
      image: vimagick/json-server
      command: -H 0.0.0.0 -p 3500 -w db.json
      ports:
      - "3500:3500"
      volumes:
        - ./db/db.json:/data/db.json
      restart: always
  reactapp:
      build: ./app
      ports:
        - "3005:3005"
  